apiVersion: v1
kind: Service
metadata:
  name: mqlsvc
  labels:
    app: mql
spec:
  type: NodePort
  ports:
    - port: 3306
      name: http
      protocol: "TCP"
      targetPort: 3306
      nodePort: 3306
  selector:
    app: mql


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqldpl
  labels:
    app: mql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mql
  template:
    metadata:
      labels:
        app: mql
    spec:
      hostname: mql
      containers:
        - name: mql
          image: localhost:32000/mysql57:latest
          volumeMounts:
            - mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
              name: config
            - mountPath: /var/lib/mysql
              name: data
          ports:
            - containerPort: 3306
              name: http
      volumes:
        - name: config
          hostPath:
            path: /root/mysql/my.cnf
        - name: data
          hostPath:
            path: /root/mysqldata