apiVersion: v1
kind: Service
metadata:
  name: rmqsvc
  labels:
    app: rmq
spec:
  type: NodePort
  ports:
    - port: 15672
      name: http
      protocol: "TCP"
      targetPort: 15672
      nodePort: 15672
    - port: 5672
      name: api
      protocol: "TCP"
      targetPort: 5672
      nodePort: 5672
  selector:
    app: rmq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmqdeploy
  labels:
    app: rmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmq
  template:
    metadata:
      labels:
        app: rmq
    spec:
      hostname: rmq
      containers:
        - name: rmq
          image: localhost:32000/rmq:latest
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rmqdb
          ports:
            - containerPort: 15672
              name: http
            - containerPort: 5672
              name: api
      volumes:
        - name: rmqdb
          hostPath:
            path: /root/dockerconf/rmqdb