apiVersion: v1
kind: Service
metadata:
  name: tmtsvc
  labels:
    app: tmt
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
      protocol: "TCP"
      targetPort: 8080
      nodePort: 8080
  selector:
    app: tmt


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmtdpl
  labels:
    app: tmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmt
  template:
    metadata:
      labels:
        app: tmt
    spec:
      hostname: tmt
      containers:
        - name: tmt
          image: localhost:32000/tomcat:latest
          volumeMounts:
            - mountPath: /opt/tomcat/webapps/ROOT.war
              name: war
            - mountPath: /opt/tomcat/webapps/upload
              name: upload
            - mountPath: /opt/tomcat/webapps/bak
              name: bak
            - mountPath: /opt/tomcat/conf/server.xml
              name: config
          ports:
            - containerPort: 8080
              name: http
      volumes:
        - name: war
          hostPath:
            path: /root/ROOT.war
        - name: upload
          hostPath:
            path: /root/infactionupload
        - name: bak
          hostPath:
            path: /root/infactionbak
        - name: config
          hostPath:
            path: /root/tomcatfile/server.xml